default: &default
  adapter: postgresql
  encoding: unicode
  username: prakash
  password: Kota@1234
  host: localhost
  pool: 5

development:
  <<: *default
  database: turf_booking

test:
  <<: *default
  database: turf_booking_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
