default: &default
  adapter: postgresql
  encoding: unicode
  username: prakash
  password: Kota@1234
  host: localhost
  pool: 5

development:
  <<: *default
  database: turf_booking
  queue:
    <<: *default
    database: turf_booking  # same as main DB

test:
  <<: *default
  database: turf_booking_test
  queue:
    <<: *default
    database: turf_booking_test  # same as test DB

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
